version: '3'
services:
  frontend:
    restart: always
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    # image: test
    container_name: streamlit
    working_dir: '/app'
    networks: 
      MLapps: 
        aliases: 
          - frontend.docker #"${alias_frontend}"
    depends_on:
      - backend
    tty: true
    volumes: 
      - ./frontend:/app
    ports: 
      - '8501:8501'
    # command: streamlit run app.py

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    # image: backend
    container_name: ml_fastapi
    working_dir: '/app'
    ports:
      - 8000:8000
    networks: 
      MLapps: 
        aliases: 
          - backend.docker
    volumes: 
      - ./backend:/app
    # command: uvicorn main:app --host 0.0.0.0 --reload

  # jupyter_notebook:
  #   restart: always
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: jupyter_notebook
  #   working_dir: '/src'
  #   tty: true
  #   volumes:
  #     - ./src:/src
  #   ports: 
  #     - '8888:8888'
  #   command: jupyter notebook --port=8888 --ip=0.0.0.0 --allow-root --NotebookApp.token=''


networks:
  MLapps: